services:
    nginx:
        depends_on:
            - node_internal_api
            - node_cors_proxy
        build: ./nginx/
        image: 873271/gamerspot:gamerspot_nginx
        restart: always
        ports:
            - "80:80"
        container_name: nginx
    node_internal_api:
        build: ./node/internal-api-conf/
        image: 873271/gamerspot:gamerspot_node_internal_api
        restart: always
        ports:
            - "3000:3000"
        container_name: node_internal_api
    node_cors_proxy:
        build: ./node/cors-proxy-conf/
        image: 873271/gamerspot:gamerspot_node_cors_proxy
        restart: always
        ports:
            - "8080:8080"
        container_name: node_cors_proxy